name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 50
      matrix:
        os: [ubuntu-latest]
        php: [ '7.3', '7.4' ]
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: php-actions/composer@v2
        with:
          php-version: ${{ matrix.php }}
      - run: php php_test.html
